### PR TITLE
Fix emoji search and make it work offline

### LINKED ISSUE #25: Support offline
We just need to depend on https://github.com/sindresorhus/emoj/blob/master/index.js

### LINKED ISSUE #27: Emoji source host down?
Hi Sindre, 

As of today, I'm receiving a failure when fetching emoji results.. Seems like the host is down.

```
RequestError: getaddrinfo ENOTFOUND emoji.getdango.com
    at ClientRequest.<anonymous> (/Users/mmccoy/Dropbox/Alfred/Alfred.alfredpreferences/workflows/alfred-emoj (Symlink Backup Copy)/node_modules/got/index.js:182:22)
```

-
Emoj 2.0.0
Alfred 4.1.1
darwin x64 19.6.0

### PR DESCRIPTION
**Pull request by mmccoy**
Apologize if I missed some process, this is my first PR. 😱 It addresses Issue #27 
I tried to observe everything in the contributions doc.

Thanks for looking, and more importantly -- thanks for all the rad and pragmatic apps you create!

Here's a  screenshot:
Screen Shot 2022-03-09 at 10 26 55 AM

Fixes #27
Fixes #25

### CODE REVIEW

**Comment by mmccoy** [comment]
@sindresorhus I patched up the tests/deps, are now passing.  Next workflow run should complete.

**Comment by mmccoy** [comment]
Just realized, this may also address #25

**Comment by sindresorhus** [comment]
Looks good. Thanks ;)

**Comment by sindresorhus** [comment]
> this is my first PR.

Congrats!

**Pull request merged**
